//LOCALIZACIONES
export const LOAD_LOCALIZACIONES = "LOAD_LOCALIZACIONES";
export const LOAD_IMAGES = "LOAD_IMAGES";
export const LOAD_DEPARTAMENTOS = "LOAD_DEPARTAMENTOS";
export const LOAD_LOCALIDADES = "LOAD_LOCALIDADES";
export const LOAD_ESTADOS = "LOAD_ESTADOS";

//BARS
export const HAMBURGUER_MENU = "HAMBURGUER_MENU";
export const SELECT_BAR_ITEM = "SELECT_BAR_ITEM";

//MARCADORES
export const SET_MARCADORES = "SET_MARCADORES";

//FILTROS
export const SET_FILTROS = "SET_FILTROS"
export const SET_DEPARTAMENTOS = "SET_DEPARTAMENTOS";
export const SET_LOCALIDADES = "SET_LOCALIDADES";
export const PUT_LOCALIDADES_FILTERED = 'PUT_LOCALIDADES_FILTERED'
export const SET_DEPENDENCIA = "SET_DEPENDENCIA";
export const SET_ESTADO = "SET_ESTADO";
export const SET_JURISDICCION = "SET_JURISDICCION";
export const SET_ORGANISMO_DEPENDENIA = "SET_ORGANISMO_DEPENDENIA";
export const SET_NIVEL = "SET_NIVEL";
export const SET_MODALIDAD = "SET_MODALIDAD";
export const SET_GESTION = "SET_GESTION";
export const SET_AMBITO = "SET_AMBITO";
export const SET_AULA_DIGITAL_MOVIL = "SET_AULA_DIGITAL_MOVIL";
export const SET_INTENET = "SET_INTENET";
export const SET_AGUA_POTABLE = "SET_AGUA_POTABLE";
export const SET_PROVEEDORES_INTERNET = "SET_PROVEEDORES_INTERNET";
export const SET_AGRUPACIONES = "SET_AGRUPACIONES";
