//LOCALIZACIONES
export const LOAD_LOCALIZACIONES = "LOAD_LOCALIZACIONES";
export const LOAD_IMAGES = "LOAD_IMAGES";

//MARCADORES
export const UPDATE_MARCADORES = "UPDATE_MARCADORES";

//BARS
export const HAMBURGUER_MENU = "HAMBURGUER_MENU"
export const SELECT_BAR_ITEM = "SELECT_BAR_ITEM"